### ISSUE TITLE
App won't open

### ISSUE THREAD

**Issue by skywarspro15** [iDevYT/iDevs-chat#3]
When I try to view the deploy preview, it just gave me a blank page.

![image](https://user-images.githubusercontent.com/86519653/189347952-12a3a47b-e697-427e-ba5f-81403e1cb094.png)

**Comment by skywarspro15** [comment]
As of now, it's been fixed.
![image](https://user-images.githubusercontent.com/86519653/189348133-aaf61c43-189f-43cd-a6a9-700afa4d2379.png)

**Comment by iDevYT** [comment]
it got fixed because the API keys were reset
